apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CI_PACKAGE_NAME}-config
  namespace: ${CI_K8S_NAMESPACE_NAME}
  labels:
    app: ${CI_PACKAGE_NAME}
data:
  CI_RANDOM_DATA: "foo"
  
  foo.txt: |
    # Some text in foo.txt
