apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${CI_PACKAGE_NAME}
  namespace: ${CI_K8S_NAMESPACE_NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${CI_PACKAGE_NAME}
    spec:
      initContainers:
        - name: ${CI_PACKAGE_NAME}-init-container
          image: busybox
          command: ["find", "/var/www"]
          volumeMounts:
            - mountPath: /var/www/html
              name: ${CI_PACKAGE_NAME}-data

      volumes:
        - name: ${CI_PACKAGE_NAME}-data
          persistentVolumeClaim:
            claimName: ${CI_PACKAGE_NAME}-data-pvc
            
      containers:
        - name: ${CI_PACKAGE_NAME}
          image: nginx
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: ${CI_PACKAGE_NAME}-data
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: ${CI_PACKAGE_NAME}-config
                  key: HOST