kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${CI_PACKAGE_NAME}-data-pv
  namespace: ${CI_K8S_NAMESPACE_NAME}
  labels:
    app: ${CI_PACKAGE_NAME}
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce