kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${CI_PACKAGE_NAME}-data-pvc
  labels:
    app: ${CI_PACKAGE_NAME}
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
