kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${CI_PACKAGE_NAME}-pvc
  namespace: ${CI_K8S_NAMESPACE_NAME}
  labels:
    app: ${CI_PACKAGE_NAME}
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
