apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-grs-retain
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Premium_GRS
reclaimPolicy: Retain
volumeBindingMode: Immediate
