name: dev

on:
  push:
    branches:
      - dev

    paths:
      - "scripts/**"
      - ".github/workflows/dev.yaml"
      - "tests/**"

env:
  # Environment
  CI_ENVIRONMENT: development

jobs:
  test:
    name: Test
    env:
      CI_PACKAGE_NAME: "web"

      # Container Registry
      CI_REPOSITORY_NAME: "sydnod-ci"
      CI_REPOSITORY_HOSTNAME: "${{ secrets.CI_REPOSITORY_HOSTNAME }}"
      CI_REPOSITORY_USERNAME: "${{ secrets.CI_REPOSITORY_USERNAME }}"
      CI_REPOSITORY_PASSWORD: "${{ secrets.CI_REPOSITORY_PASSWORD }}"

      # Kubernetes
      CI_K8S_NAMESPACE_NAME: "sydnod-ci"
      CI_K8S_SOURCE_PATH: "./tests/ops/config/kubernetes"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      # Bootstrap
      - name: CI Bootstrap
        run: chmod -R +x ./scripts && ./scripts/bootstrap.sh

      # Test Bootstrap CI script
      - name: CI Bootstrap Tests
        run: chmod -R +x ./tests/scripts && ./tests/scripts/bootstrap.sh

      # Set the target AKS cluster.
      - name: Login to Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.CI_KUBE_CONFIG }}

      # Login to Container Registry
      - name: Login to Docker Container Registry (CR)
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ env.CI_REPOSITORY_HOSTNAME }}
          username: ${{ env.CI_REPOSITORY_USERNAME }}
          password: ${{ env.CI_REPOSITORY_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build
          -f ./tests/Dockerfile
          -t "${CI_REPOSITORY_IMAGE_PATH_FULL}"
          --build-arg CI_ENVIRONMENT=${{ env.CI_ENVIRONMENT }}
          --build-arg CI_COMMIT_SHA_SHORT=${{ env.CI_COMMIT_SHA_SHORT }}
          ./tests/src

      # Push Docker image
      - name: Push Docker image to CR
        run: docker push ${CI_REPOSITORY_IMAGE_PATH_FULL}

      # Create secret
      - name: Create a CR secret in Kubernetes
        uses: Azure/k8s-create-secret@v1
        with:
          namespace: ${{ env.CI_K8S_NAMESPACE_NAME }}
          container-registry-url: ${{ env.CI_REPOSITORY_HOSTNAME }}
          container-registry-username: ${{ env.CI_REPOSITORY_USERNAME }}
          container-registry-password: ${{ env.CI_REPOSITORY_PASSWORD }}
          secret-name: ${{ env.CI_K8S_REPOSITORY_SECRET_NAME }}

      # Deply to Kubernetes
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          namespace: ${{ env.CI_K8S_NAMESPACE_NAME }}
          manifests: |
            ${{ env.CI_K8S_GENERATED_MANIFESTS_FILE }}
          images: |
            ${{ env.CI_REPOSITORY_IMAGE_PATH_FULL }}
          imagepullsecrets: |
            ${{ env.CI_K8S_REPOSITORY_SECRET_NAME }}
